title: "Mediatek Mali GPU Governor"
description: "Advanced GPU governor for Mediatek processors"
baseurl: "/Mediatek_Mali_GPU_Governor"
url: "https://seyud.github.io"

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

lang: zh-CN